"""Add product images specs and cart unique constraint

Revision ID: e6ceb5f50145
Revises: 
Create Date: 2026-01-28 16:06:06.346968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6ceb5f50145'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('specifications', sa.JSON(), nullable=True))
    
    # Cart Unique Constraint
    # Try to drop existing if autogenerated name matches common conventions, otherwise just create new
    try:
        op.create_unique_constraint('uq_cart_item_product', 'cart_items', ['cart_id', 'product_id'])
    except Exception:
        pass # Constraint might already exist
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('customer', 'staff', 'admin', name='user_role'),
               nullable=True,
               existing_server_default=sa.text("'customer'::user_role"))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_unique_constraint('products_sku_key', 'products', ['sku'])
    op.create_index('idx_products_sku', 'products', ['sku'], unique=False)
    op.create_index('idx_products_name_search', 'products', [sa.text("to_tsvector('simple'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_products_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_products_age_restricted', 'products', ['is_age_restricted'], unique=False)
    op.create_index('idx_products_active', 'products', ['is_active'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'min_age',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'is_age_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'cái'::character varying"))
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'images')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.create_index('idx_orders_user', 'orders', ['user_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_payment', 'orders', ['payment_status'], unique=False)
    op.create_index('idx_orders_created', 'orders', [sa.text('created_at DESC')], unique=False)
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'is_age_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.alter_column('orders', 'payment_method',
               existing_type=postgresql.ENUM('cod', 'momo', 'vnpay', 'bank_transfer', name='payment_method'),
               nullable=True,
               existing_server_default=sa.text("'cod'::payment_method"))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'picking', 'delivering', 'completed', 'cancelled', name='order_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::order_status"))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_batch_id_fkey', 'order_items', 'inventory_batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index('idx_order_items_product', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_order_items_order', 'order_items', ['order_id'], unique=False)
    op.alter_column('order_items', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'inventory_batches', type_='foreignkey')
    op.create_foreign_key('inventory_batches_product_id_fkey', 'inventory_batches', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_inventory_batches_product_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_expiry_date'), table_name='inventory_batches')
    op.create_unique_constraint('inventory_batches_product_id_batch_code_key', 'inventory_batches', ['product_id', 'batch_code'])
    op.create_index('idx_inventory_product', 'inventory_batches', ['product_id'], unique=False)
    op.create_index('idx_inventory_expiry', 'inventory_batches', ['expiry_date'], unique=False)
    op.create_index('idx_inventory_available', 'inventory_batches', ['product_id', 'expiry_date'], unique=False, postgresql_where='(quantity_on_hand > quantity_reserved)')
    op.alter_column('inventory_batches', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory_batches', 'received_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index('idx_categories_sort', 'categories', ['sort_order'], unique=False)
    op.create_index('idx_categories_slug', 'categories', ['slug'], unique=False)
    op.create_index('idx_categories_active', 'categories', ['is_active'], unique=False)
    op.create_unique_constraint('categories_slug_key', 'categories', ['slug'])
    op.alter_column('categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_user_id_fkey', 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.create_unique_constraint('carts_user_id_key', 'carts', ['user_id'])
    op.alter_column('carts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('carts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_product_id_fkey', 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_items_cart_id_fkey', 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_cart_item_product', 'cart_items', type_='unique')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.create_index('idx_cart_items_product', 'cart_items', ['product_id'], unique=False)
    op.create_index('idx_cart_items_cart', 'cart_items', ['cart_id'], unique=False)
    op.create_unique_constraint('cart_items_cart_id_product_id_key', 'cart_items', ['cart_id', 'product_id'])
    op.alter_column('cart_items', 'added_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
